In [1]:
# array: array is a colletion of similar data types
import array as arr

In [2]:
arr1 = arr.array('i',[1,2,3,4,5])

In [3]:
arr1

array('i', [1, 2, 3, 4, 5])

In [4]:
type(arr1)

array.array

In [ ]:
# numpy array - ndarray

In [5]:
# Numpy: Numerical Python - linear algebra, data sort, data calculations, transformations - log, exp, shape, logical operations etc
! pip install numpy


[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
# array
a1 = np.array([1,2,3,4,5,6])

In [3]:
a1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(a1)

numpy.ndarray

In [5]:
# 1D
n1 = np.array([1,2,3])
n1.ndim # dimension

1

In [6]:
# 2D:
n2 = np.array([[1,2],
              [3,4]])
n2.ndim

2

In [7]:
n2

array([[1, 2],
       [3, 4]])

In [8]:
n2[1][0]

3

In [9]:
# 3D
n3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]]])

In [10]:
n3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
n3.ndim

3

In [12]:
n3.shape

(1, 3, 3)

In [13]:
n3.size

9

In [14]:
n3.dtype

dtype('int32')

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [20]:
np.arange(100,1,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [30]:
a11 = np.array([67,34,22,11,65,76,33,27,90])
np.sort(a11)[::-1]

array([90, 76, 67, 65, 34, 33, 27, 22, 11])

In [33]:
# concatenate
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
new = np.concatenate([a1,a2])
new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
n4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [41]:
n4 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9],
               [10,11,12]]])

In [42]:
n4.ndim

3

In [51]:
n5 = n4.reshape(3,4)
n5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
n5.shape

(3, 4)

In [57]:
n6 = np.arange(1,30,2)
n6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [59]:
n6[n6 >= 20]

array([21, 23, 25, 27, 29])

In [63]:
n6[(n6>2) & (n6 < 18)]

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
# Numpy session 2

In [1]:
import numpy as np

In [3]:
# random.random
np.random.random(10)

array([0.50901211, 0.80923439, 0.64437959, 0.32263537, 0.16312159,
       0.08103067, 0.57145208, 0.10106975, 0.77912905, 0.77698489])

In [10]:
np.random.randint(1,100,40)

array([54, 68, 93, 91, 92,  9, 88,  6, 57, 18, 59, 60, 48, 82, 38, 14, 30,
        4, 72,  8, 35, 86, 72, 62, 34, 63, 72, 31, 53, 57, 21, 52, 38, 76,
       97, 20,  8, 75, 12, 64])

In [16]:
np.random.seed(20)
np.random.randint(200,400,20)

array([299, 215, 356, 337, 348, 275, 222, 271, 362, 318, 240, 226, 216,
       390, 344, 305, 301, 207, 206, 226])

In [21]:
np.random.seed(21)
a1 = np.random.randint(1,1000,30)
a1

array([970, 208, 825, 773,  49, 369, 121, 420, 701, 611, 512, 754, 203,
       841, 623, 448, 429, 830, 254, 234, 766, 759, 123, 305, 239, 869,
       999, 597, 316, 661])

In [22]:
a1.max()

999

In [23]:
a1.min()

49

In [24]:
a1.argmax()

26

In [25]:
a1.argmin()

4

In [26]:
np.median(a1)

554.5

In [27]:
# missing values
a1 = np.array([10,20,np.nan,40,50,np.nan,70,80])

In [28]:
a1

array([10., 20., nan, 40., 50., nan, 70., 80.])

In [29]:
np.isnan(a1)

array([False, False,  True, False, False,  True, False, False])

In [30]:
np.where(np.isnan(a1))

(array([2, 5], dtype=int64),)

In [31]:
a1[np.isnan(a1)] = 0

In [32]:
a1

array([10., 20.,  0., 40., 50.,  0., 70., 80.])

In [33]:
np.isnan(a1)

array([False, False, False, False, False, False, False, False])